services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - '3002:3000'
    env_file:
      - .env
    networks:
      - docker_default
      - proxy

networks:
  docker_default:
    external: true
  proxy:
    external: true
